name: Java CI with Maven

on:
  push:
    branches:
      - '**'  # Rodar em qualquer branch
  pull_request:
    branches:
      - '**'  # Também rodar em qualquer PR de qualquer branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'  # Definir a distribuição do JDK

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Cache SonarQube packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Build with Maven
      run: mvn clean verify

    - name: SonarQube Scan
      run: mvn sonar:sonar \
        -Dsonar.projectKey=maia \
        -Dsonar.host.url=http://localhost:9000 \
        -Dsonar.login=sqp_1eab803a27c4c8c8b884bdbb7b6017130b4635c0

    - name: Quality Gate
      run: |
        curl -u sqp_1eab803a27c4c8c8b884bdbb7b6017130b4635c0 "http://localhost:9000/api/qualitygates/project_status?projectKey=maia" | grep -q '"status":"OK"' || exit 1
